import { ActivatedRoute } from '@angular/router';
import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [

  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: []
  },

  // Admin Modules
  {
    path: '',
    title: 'Overview',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [
      {
        path: '/dashboard/main',
        title: 'Dashboard',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: []
      },
    ]
  },
  {
    path: '',
    title: 'Parameterization',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },
  {
    path: '',
    title: 'Structure',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/structure/service',
        title: 'All Service',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

    ]
  },


  {
    path: 'admin/equipment/Equipments',
    "title": "equipment",
    "iconType": "material-icons-two-tone",
    "icon": " construction", // Remplacez "local_grocery_store" par le nom de l'icône Material Icons souhaitée
    "class": "",
    "groupTitle": false,
    "badge": "",
    "badgeClass": "",
    "role": ["Admin"],
    "submenu": []
  },

  //   {
  //     path: '',
  //     title: 'Medical Records',
  //     iconType: 'material-icons-two-tone',
  //     icon: 'settings',
  //     class: 'menu-toggle',
  //     groupTitle: false,
  //     badge: '',
  //     badgeClass: '',
  //     role: ['Admin'],
  //     submenu: [
  //   // {
  //   //   path: '',
  //   //   title: 'Vaccination',
  //   //   iconType: 'material-icons-two-tone',
  //   //   icon: 'local_pharmacy',
  //   //   class: 'menu-toggle',
  //   //   groupTitle: false,
  //   //   badge: '',
  //   //   badgeClass: '',
  //   //   role: ['Admin'],
  //   //   submenu: [
  //   //     {
  //   //       path: '/admin/vaccination/vacc-list',
  //   //       title: 'Vaccination List',
  //   //       iconType: '',
  //   //       icon: '',
  //   //       class: 'ml-menu',
  //   //       groupTitle: false,
  //   //       badge: '',
  //   //       badgeClass: '',
  //   //       role: [''],
  //   //       submenu: [],
  //   //     },
  //   //   ]
  //   // },

  // // {
  // //   path: '',
  // //   title: 'Allergy',
  // //   iconType: 'material-icons-two-tone',
  // //   icon: 'local_pharmacy',
  // //   class: 'menu-toggle',
  // //   groupTitle: false,
  // //   badge: '',
  // //   badgeClass: '',
  // //   role: ['Admin'],
  // //   submenu: [
  // //     {
  // //       path: '/admin/allergy/allergy-list',
  // //       title: 'Allergy List',
  // //       iconType: '',
  // //       icon: '',
  // //       class: 'ml-menu',
  // //       groupTitle: false,
  // //       badge: '',
  // //       badgeClass: '',
  // //       role: [''],
  // //       submenu: [],
  // //     },
  // //   ]
  // //   },
  //   // {
  //   //   path: '',
  //   //   title: 'Biological Analyses',
  //   //   iconType: 'material-icons-two-tone',
  //   //   icon: 'local_pharmacy',
  //   //   class: 'menu-toggle',
  //   //   groupTitle: false,
  //   //   badge: '',
  //   //   badgeClass: '',
  //   //   role: ['Admin'],
  //   //   submenu: [
  //   //     {
  //   //       path: '/admin/bio-analyses/bio-analyses-list',
  //   //       title: 'Biological Analyses List',
  //   //       iconType: '',
  //   //       icon: '',
  //   //       class: 'ml-menu',
  //   //       groupTitle: false,
  //   //       badge: '',
  //   //       badgeClass: '',
  //   //       role: [''],
  //   //       submenu: [],
  //   //     },
  //   //   ]
  //   //   },
  //   ]
  //   },
  // {
  //   path: '',
  //   title: 'Medical Acts',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'local_pharmacy',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/diseaseCode/disease-code-list',
  //       title: 'ICD-10 Codes List',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ]
  // },
  // {
  //   path: '',
  //   title: 'Document Template',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'book',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/file/file',
  //       title: 'Document Template List',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ]
  // },

  // Medications Modules
  //  {
  //   path: '',
  //   title: 'Medications',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'medication',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/medications/all-medications',
  //       title: 'All Medications',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },

  // Categories Module
  // {
  //   path: '',
  //   title: 'Categories',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'category',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/categories/all-categories',
  //       title: 'All Categories',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },

  // physicalTreatments Module
  // {
  //   path: '',
  //   title: 'Physical Treatments',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'category',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/physicalTreatments/all-physicalTreatments',
  //       title: 'All Physical Treatments',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },


  // {
  //   path: '#',
  //   title: 'Material Resources',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'room_preferences',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '#',
  //       title: 'Room Group',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: []
  //     },
  //     {
  //       path: '#',
  //       title: 'Room',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: []
  //     },
  //     {
  //       path: '#',
  //       title: 'Equipment',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: []
  //     }
  //   ]
  // },
  ///structure/material-resource/equipment/equipment


  {
    path: '#',
    title: 'Human Resources',
    iconType: 'material-icons-two-tone',
    icon: 'supervised_user_circle'  ,
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [

      {
        path: '/admin/staffs/all-staffs',
        title: 'All doctors',
        iconType: '',
        icon: 'people',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/staffGroup/all-staffGroup',
        title: 'All staffGroup',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      /*{
        path: '/admin/patient/all-patient',
        title: 'All patient',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },*/


    ]
  },

  /*{
    path: '#',
    title: '  Appointment',
    iconType: 'material-icons-two-tone',
    icon: 'assignment',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [

      // {
      //   path: '/admin/appointmentAdmin/all-appointment',
      //   title: 'Calender of Appointment',
      //   iconType: '',
      //   icon: 'people',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      {
        path: '/admin/calendar/calendar',
        title: 'Calender of Appointment',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },


    ]
  },
  {
    path: '#',
    title: '  Availability',
    iconType: 'material-icons-two-tone',
    icon: 'assignment',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [


      {
        path: '/admin/availability/all-availability',
        title: 'availability',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

    ]
  },*/
  // {
  //   path: '',
  //   title: 'Insurance',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'book',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/insurances/insu-list',
  //       title: 'Insurance List',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },

  // Doctor Modules
  // {
  //   path: '/doctor/patient/all-patient',
  //   title: 'MENUITEMS.DOCTOR.DASHBOARD',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'space_dashboard',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Doctor'],
  //   submenu: []
  // },
  {
    path: '/doctor/patient/all-patient',
    title: 'MENUITEMS.DOCTOR.PATIENTS',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },

  {
    path: '/doctor/requests',
    title: 'Appointment requests',
    iconType: 'material-icons-two-tone',
    icon: 'folder',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },
  {
    path: '/doctor/calendar/calendar',
    title: 'Calender of Appointment ',
    iconType: 'material-icons-two-tone',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },



  /*{
    path: '/doctor/appointments',
    title: 'MENUITEMS.DOCTOR.APPOINTMENTS',
    iconType: 'material-icons-two-tone',
   icon: 'assignment',
    class: '',
   groupTitle: false,
    badge: '',
   badgeClass: '',
   role: ['Doctor'],
    submenu: []
  },*/
  /*{
    path: '/doctor/doctors',
    title: 'MENUITEMS.DOCTOR.DOCTORS',
    iconType: 'material-icons-two-tone',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: []
  },*/
  /* {
     path: '/doctor/patients',
     title: 'MENUITEMS.DOCTOR.PATIENTS',
     iconType: 'material-icons-two-tone',
     icon: 'face',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
     submenu: []
   },*/
  // {
  //   path: '#',
  //   title: '  Appointment',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'assignment',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Doctor'],
  //   submenu: [


  //     {
  //       path: '/doctor/calendar/calendar',
  //       title: 'Calender of Appointment',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: ['Doctor'],
  //       submenu: [],
  //     },




  //   ]
  // },
  //  {
  //   path: '/doctor/work-availability/all-availability',
  //   title: 'Work Availability',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'supervised_user_circle',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Doctor'],
  //   submenu: [],
  // },
  /*{
    path: '/doctor/doctors',
    title: 'MENUITEMS.DOCTOR.DOCTORS',
    iconType: 'material-icons-two-tone',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: []
  },*/
  // {
  //   path: '#',
  //   title: '  Availability',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'assignment',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Doctor'],
  //   submenu: [


  //     {
  //       path: '/doctor/availability/all-availability',
  //       title: 'availability',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },

  //   ]
  // },
  /*{
    path: '/doctor/settings',
    title: 'MENUITEMS.DOCTOR.SETTINGS',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
   class: '',
   groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: []
  },
  {
    path: '/apps/chat',
    title: 'MENUITEMS.DOCTOR.CHAT',
    iconType: 'material-icons-two-tone',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: []
  },
*/

// Doctor Modules
{
  path: '/secretary/dashboard',
  title: 'MENUITEMS.DOCTOR.DASHBOARD',
  iconType: 'material-icons-two-tone',
  icon: 'space_dashboard',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Secretary'],
  submenu: []
},
{
  path: '/secretary/patient/all-patient',
  title: 'MENUITEMS.DOCTOR.PATIENTS',
  iconType: 'material-icons-two-tone',
  icon: 'face',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Secretary'],
  submenu: [],
},


{
  path: '#',
  title: '  Appointment',
  iconType: 'material-icons-two-tone',
  icon: 'assignment',
  class: 'menu-toggle',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Secretary'],
  submenu: [


    {
      path: '/secretary/calendar/calendar',
      title: 'Calender of Appointment',
      iconType: '',
      icon: '',
      class: 'ml-menu',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: ['Secretary'],
      submenu: [],
    },
    {
      path: '/secretary/bookAppointment',
      title: 'Book Appointment',
      iconType: '',
      icon: '',
      class: 'ml-menu',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: ['Secretary'],
      submenu: [],
    },



  ]
},
 {
  path: '/secretary/work-availability/all-availability',
  title: 'Doctor',
  iconType: 'material-icons-two-tone',
  icon: 'supervised_user_circle',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Secretary'],
  submenu: [],
},
  // Patient Modules
  {
    path: '/patient/dashboard',
    title: 'MENUITEMS.PATIENT.DASHBOARD',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: []
  },
  {
    path: '',
    title: 'MENUITEMS.PATIENT.APPOINTMENTS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'assignment',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: [
      {
        path: '/patient/appointments/book',
        title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.BOOK-APPOINTMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: []
      },
      {
        path: '/patient/appointments/today',
        title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.TODAY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: []
      },
      {
        path: '/patient/appointments/upcoming',
        title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.UPCOMING',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: []
      },
      {
        path: '/patient/appointments/past',
        title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.PAST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: []
      },
    ]
  },
  {
    path: '/patient/prescriptions',
    title: 'MENUITEMS.PATIENT.PRESCRIPTIONS',
    iconType: 'material-icons-two-tone',
    icon: 'receipt_long',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: []
  },
  {
    path: '/patient/records',
    title: 'MENUITEMS.PATIENT.MEDICAL-RECORD',
    iconType: 'material-icons-two-tone',
    icon: 'restore_page',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: []
  },
  {
    path: '/patient/billing',
    title: 'MENUITEMS.PATIENT.BILLING',
    iconType: 'material-icons-two-tone',
    icon: 'receipt',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: []
  },
  {
    path: '/apps/chat',
    title: 'MENUITEMS.PATIENT.CHAT',
    iconType: 'material-icons-two-tone',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: []
  },
  {
    path: '/patient/settings',
    title: 'MENUITEMS.PATIENT.SETTINGS',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: []
  },
  // Common Modules

  // {
  //   path: '',
  //   title: 'Apps',
  //   iconType: '',
  //   icon: '',
  //   class: '',
  //   groupTitle: true,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin', 'Doctor'],
  //   submenu: [],
  // },
  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: 'New',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: [],
    submenu: [],
  },
  // {
  //   path: 'task',
  //   title: 'Task',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'fact_check',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin', 'Doctor'],
  //   submenu: [],
  // },
  /*   {
       path: 'contacts',
       title: 'Contacts',
      iconType: 'material-icons-two-tone',
     icon: 'contacts',
       class: '',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: ['Admin', 'Doctor'],
      submenu: [],
    },
    {
      path: '',
      title: 'Email',
      iconType: 'material-icons-two-tone',
      icon: 'email',
      class: 'menu-toggle',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: ['Admin', 'Doctor'],
      submenu: [
        {
          path: '/email/inbox',
          title: 'Inbox',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          role: [''],
          submenu: [],
        },
        {
          path: '/email/compose',
          title: 'Compose',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          role: [''],
          submenu: [],
        },
        {
          path: '/email/read-mail',
          title: 'Read Email',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          role: [''],
          submenu: [],
        },
      ],
    },*/
  /*{
    path: '',
    title: 'More Apps',
    iconType: 'material-icons-two-tone',
    icon: 'stars',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '4',
    badgeClass: 'badge bg-orange sidebar-badge float-end',
    role: ['Admin'],
    submenu: [
      {
        path: '/apps/chat',
        title: 'Chat',
        iconType: 'material-icons-two-tone',
        icon: 'chat',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/apps/contact-grid',
        title: 'Contact Grid',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/apps/dragdrop',
        title: 'Drag & Drop',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/apps/support',
        title: 'Support',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },*/
  /* {
     path: '',
     title: 'Widgets',
     iconType: 'material-icons-two-tone',
     icon: 'widgets',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/widget/chart-widget',
         title: 'Chart Widget',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/widget/data-widget',
         title: 'Data Widget',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Components',
     iconType: '',
     icon: '',
     class: '',
     groupTitle: true,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [],
   },
   {
     path: '',
     title: 'User Interface (UI)',
     iconType: 'material-icons-two-tone',
     icon: 'dvr',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/ui/alerts',
         title: 'Alerts',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/badges',
         title: 'Badges',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/chips',
         title: 'Chips',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/modal',
         title: 'Modal',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/buttons',
         title: 'Buttons',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/expansion-panel',
         title: 'Expansion Panel',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/bottom-sheet',
         title: 'Bottom Sheet',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/dialogs',
         title: 'Dialogs',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/cards',
         title: 'Cards',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/labels',
         title: 'Labels',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/list-group',
         title: 'List Group',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/snackbar',
         title: 'Snackbar',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/preloaders',
         title: 'Preloaders',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/progressbars',
         title: 'Progress Bars',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/tabs',
         title: 'Tabs',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/typography',
         title: 'Typography',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/ui/helper-classes',
         title: 'Helper Classes',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Forms',
     iconType: 'material-icons-two-tone',
     icon: 'subtitles',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/forms/form-controls',
         title: 'Form Controls',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/forms/advance-controls',
         title: 'Advanced Controls',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/forms/form-example',
         title: 'Form Examples',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/forms/form-validation',
         title: 'Form Validation',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/forms/wizard',
         title: 'Form Wizard',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/forms/editors',
         title: 'Editors',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Tables',
     iconType: 'material-icons-two-tone',
     icon: 'view_list',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/tables/basic-tables',
         title: 'Basic Tables',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/tables/material-tables',
         title: 'Material Tables',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/tables/ngx-datatable',
         title: 'ngx-datatable',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Charts',
     iconType: 'material-icons-two-tone',
     icon: 'insert_chart',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '7',
     badgeClass: 'badge bg-green sidebar-badge float-end',
     role: ['Admin'],
     submenu: [
       {
         path: '/charts/echart',
         title: 'Echart',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/charts/apex',
         title: 'Apex',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/charts/chartjs',
         title: 'ChartJS',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/charts/ngx-charts',
         title: 'Ngx-Charts',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/charts/gauge',
         title: 'Gauge',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Timeline',
     iconType: 'material-icons-two-tone',
     icon: 'amp_stories',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/timeline/timeline1',
         title: 'Timeline 1',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/timeline/timeline2',
         title: 'Timeline 2',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Icons',
     iconType: 'material-icons-two-tone',
     icon: 'eco',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/icons/material',
         title: 'Material Icons',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/icons/font-awesome',
         title: 'Font Awesome',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Authentication',
     iconType: 'material-icons-two-tone',
     icon: 'supervised_user_circle',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/authentication/signin',
         title: 'Sign In',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/authentication/signup',
         title: 'Sign Up',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/authentication/forgot-password',
         title: 'Forgot Password',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/authentication/locked',
         title: 'Locked',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/authentication/page404',
         title: '404 - Not Found',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/authentication/page500',
         title: '500 - Server Error',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Extra Pages',
     iconType: 'material-icons-two-tone',
     icon: 'description',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/extra-pages/profile',
         title: 'Profile',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/extra-pages/pricing',
         title: 'Pricing',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/extra-pages/invoice',
         title: 'Invoice',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/extra-pages/faqs',
         title: 'Faqs',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/extra-pages/blank',
         title: 'Blank Page',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Maps',
     iconType: 'material-icons-two-tone',
     icon: 'map',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/maps/google',
         title: 'Google Map',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
     ],
   },
   {
     path: '',
     title: 'Multi level Menu',
     iconType: 'material-icons-two-tone',
     icon: 'slideshow',
     class: 'menu-toggle',
     groupTitle: false,
     badge: '',
     badgeClass: '',
     role: ['Admin'],
     submenu: [
       {
         path: '/multilevel/first1',
         title: 'First',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
       },
       {
         path: '/',
         title: 'Second',
         iconType: '',
         icon: '',
         class: 'ml-sub-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [
           {
             path: '/multilevel/secondlevel/second1',
             title: 'Second 1',
             iconType: '',
             icon: '',
             class: 'ml-menu2',
             groupTitle: false,
             badge: '',
             badgeClass: '',
             role: [''],
             submenu: [],
           },
           {
             path: '/',
             title: 'Second 2',
             iconType: '',
             icon: '',
             class: 'ml-sub-menu2',
             groupTitle: false,
             badge: '',
             badgeClass: '',
             role: [''],
             submenu: [
               {
                 path: '/multilevel/thirdlevel/third1',
                 title: 'third 1',
                 iconType: '',
                 icon: '',
                 class: 'ml-menu3',
                 groupTitle: false,
                 badge: '',
                 badgeClass: '',
                 role: [''],
                 submenu: [],
               },
             ],
           },
         ],
       },
       {
         path: '/multilevel/first3',
         title: 'Third',
         iconType: '',
         icon: '',
         class: 'ml-menu',
         groupTitle: false,
         badge: '',
         badgeClass: '',
         role: [''],
         submenu: [],
      },
      ],
    },*/
];

